##
## csc609/507-221 (sept 2021-dec 2021)
##
## makefile for proj5
##
## last-update:
##    16 nov 2021: template files
##
##

PYTHON= python3
TEST_PROGRAM= proj5_test.py


test:
	${PYTHON} ${TEST_PROGRAM}

clean:
	-rm -rf __pycache__

